### ISSUE TITLE
AWS Django server not finding worm data

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_cloud#25]
The server is running (yay!) and pointed at the `dev` branch.

http://movement.openworm.org/webworm/

But now @cheelee perhaps you can tell me why the data is not showing up.  Thanks

![image](https://cloud.githubusercontent.com/assets/5267078/25783323/9192c0a2-3384-11e7-9f4b-695b4efea9c2.png)

**Comment by MichaelCurrie** [comment]
Or am I wrong?  Maybe I'm just not searching properly.  The tool seems to have UI elements I can click on, but I can't seem to generate anything other than "No Search Results".  I haven't tried very hard yet, though.

**Comment by cheelee** [comment]
This looks like a server-specific bug. I'll have to look into it on the server proper the next time. Working on my machine, but not on the server.

**Comment by cheelee** [comment]
There appears to be massive confusion on the server over what is running Python and what is running Python3. My version on my Mac works fine because it is sandboxed in a virtualenv running Python 2 only. The server somehow starts, but with errors from Python 2 even though we clearly instructed it to start the server with Python 3. 

I'm going to have to spend some time to see how we can untangle this mess.

**Comment by cheelee** [comment]
Fixed. Please see git commit messages, and code comments for full details.
