### ISSUE TITLE
Django handle POST requests from WCON viewer pane

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_cloud#99]
We need Django to save the POST requests to a holding area for WCON files that have been uploaded.

Currently, an upload leads to a client-side browser error.

**Comment by cheelee** [comment]
We need to consider how that is to be handled - if you look at https://github.com/openworm/movement_cloud/blob/master/webworm/views.py the function index(request) can be modified to handle the POST or GET request. The question really is how do we want to manage the WCON file that is uploaded on the server side if that is the intent.

If this is a client rather than a server thing, then we should probably handle it accordingly in memory on the client. I've not yet handled I/O issues on the client, but as I understand it I/O is highly restricted for clients.

**Comment by cheelee** [comment]
The HTML5 fix resolves this issue.
